import SwiftUI

/// First-run onboarding screen. Explains privacy guarantees and app purpose
/// before any session data is collected.
struct OnboardingView: View {

    @AppStorage("hasCompletedOnboarding") private var hasCompletedOnboarding = false
    @State private var currentPage = 0

    private let pages: [OnboardingPage] = [
        OnboardingPage(
            systemImage: "lock.shield.fill",
            imageColor: .blue,
            title: "Your Data Stays Here",
            body: "FocusLens runs every prediction on your device. No study data, behavior, or focus patterns are ever sent to a server or shared with third parties."
        ),
        OnboardingPage(
            systemImage: "brain.head.profile",
            imageColor: .purple,
            title: "On-Device Intelligence",
            body: "Focus predictions are generated by a lightweight machine learning model that runs entirely on your iPhone — even in airplane mode."
        ),
        OnboardingPage(
            systemImage: "book.closed.fill",
            imageColor: .green,
            title: "A Study Assistant, Not a Diagnostic Tool",
            body: "FocusLens helps you reflect on study patterns. It is not a medical, clinical, or psychological assessment tool. Results are exploratory, not prescriptive."
        ),
        OnboardingPage(
            systemImage: "trash.fill",
            imageColor: .orange,
            title: "You Control Your History",
            body: "All session history is stored only on this device. You can delete individual sessions or all data at any time from the History screen."
        )
    ]

    var body: some View {
        VStack(spacing: 0) {
            TabView(selection: $currentPage) {
                ForEach(Array(pages.enumerated()), id: \.offset) { index, page in
                    pageView(page)
                        .tag(index)
                }
            }
            .tabViewStyle(.page(indexDisplayMode: .never))
            .animation(.easeInOut, value: currentPage)

            bottomControls
        }
        .background(Color(.systemBackground))
    }

    // MARK: - Page Content

    @ViewBuilder
    private func pageView(_ page: OnboardingPage) -> some View {
        VStack(spacing: 32) {
            Spacer()

            Image(systemName: page.systemImage)
                .resizable()
                .scaledToFit()
                .frame(width: 80, height: 80)
                .foregroundStyle(page.imageColor)
                .accessibilityHidden(true)

            VStack(spacing: 16) {
                Text(page.title)
                    .font(.title2)
                    .fontWeight(.bold)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(.primary)

                Text(page.body)
                    .font(.body)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(.horizontal, 32)

            Spacer()
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(page.title). \(page.body)")
    }

    // MARK: - Bottom Controls

    private var bottomControls: some View {
        VStack(spacing: 20) {
            pageIndicator

            if currentPage < pages.count - 1 {
                Button(action: nextPage) {
                    Text("Next")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(PrimaryButtonStyle())
                .accessibilityLabel("Go to next onboarding page")
            } else {
                Button(action: completeOnboarding) {
                    Text("Get Started")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(PrimaryButtonStyle())
                .accessibilityLabel("Complete onboarding and open FocusLens")
            }
        }
        .padding(.horizontal, 24)
        .padding(.bottom, 40)
    }

    private var pageIndicator: some View {
        HStack(spacing: 8) {
            ForEach(0..<pages.count, id: \.self) { index in
                Capsule()
                    .fill(index == currentPage ? Color.accentColor : Color(.systemGray4))
                    .frame(width: index == currentPage ? 24 : 8, height: 8)
                    .animation(.easeInOut(duration: 0.25), value: currentPage)
                    .accessibilityHidden(true)
            }
        }
    }

    // MARK: - Actions

    private func nextPage() {
        currentPage = min(currentPage + 1, pages.count - 1)
    }

    private func completeOnboarding() {
        hasCompletedOnboarding = true
    }
}

// MARK: - Supporting Types

private struct OnboardingPage {
    let systemImage: String
    let imageColor: Color
    let title: String
    let body: String
}

// MARK: - Button Style

struct PrimaryButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .padding(.vertical, 16)
            .padding(.horizontal, 24)
            .background(Color.accentColor)
            .foregroundStyle(.white)
            .font(.headline)
            .clipShape(RoundedRectangle(cornerRadius: 14))
            .opacity(configuration.isPressed ? 0.85 : 1.0)
    }
}

// MARK: - Preview

#Preview {
    OnboardingView()
}
